application:
  title: rate-limited-reactive-notification-service
  pretty-title: Reactive Notification Service with Redis Rate Limiter
  description: Demo project for interview challenge
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /notification-service/api
  port: ${APPLICATION_PORT}

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  application:
    name: ${application.title}
  webflux:
    base-path: /notification-service/api
  web:
    locale: en